/*
*******************
Problem 2

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*******************
Pass

*******************
For recursive, return to function call.

*******************
*/

#include <stdio.h>

int calc(int _num, int num, int sum){

	int num_;

	if (num % 2 == 0){
		sum += num;
	}
	
	num_ = _num + num;

	if (num_ < 4000000){
		return calc(num, num_, sum);
	}	
	else{
		return sum;
	}
}

int main(void){

        int _num = 1;
        int num = 2;
        int sum = 0;

        sum = calc(_num, num, sum);

        printf("%d",sum);

        return 0;
}

